In [11]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor
from IPython.display import display

from Preprocess import Preprocessor
from RandomCV import RandomCV

In [12]:
drop_cols_ExB = ['Plot', 'Year', 'Date', 'Range', 'Row', 'left', 
                 'top', 'right', 'bottom', 'Mean.Yld.bu.ac', 
                 'Yld Vol(Dr', 'Crop Flw(M', 'Crop Flw(V', 'Elevation(',
                 'Moisture(%', 'BI', 'GLI', 'GLI', 'NGRDI', 'MGRVI', 'RGBVI', 'GRRI', 'VEG', 'ExGR', 'ExG', 'ExR', 'Green'
                ]

drop_cols = ['Plot', 'Year', 'Date', 'Range', 'Row', 'left', 
                 'top', 'right', 'bottom', 'Mean.Yld.bu.ac', 
                 'Yld Vol(Dr', 'Crop Flw(M', 'Crop Flw(V', 'Elevation(',
                 'Moisture(%', 'BI', 'GLI', 'GLI', 'NGRDI', 'MGRVI', 'RGBVI', 'GRRI', 'VEG',
                 'ExB', 'ExGR', 'ExG', 'ExR', 'Green'
            ]

### Load Field Indices and Define Models to be Tested Through Cross Validation

In [13]:
indices_6302020 = pd.read_csv("../Datasets/Indices_Combined/2020/June_30_2020_New.csv")
indices_6302021 = pd.read_csv("../Datasets/Indices_Combined/2021/June_30_2021.csv")
indices_6282022 = pd.read_csv("../Datasets/Indices_Combined/2022/June_28_2022.csv")

indices_7062020 = pd.read_csv("../Datasets/Indices_Combined/2020/July_6_2020_New.csv")
indices_7122021 = pd.read_csv("../Datasets/Indices_Combined/2021/July_12_2021.csv")
indices_7132022 = pd.read_csv("../Datasets/Indices_Combined/2022/July_13_2022.csv")

cv_models = {'LR': LinearRegression(n_jobs=-1), 'RF': RandomForestRegressor(n_jobs=-1, random_state=41, max_features='sqrt', max_depth=6, max_samples=50), 'XGB': XGBRegressor(eta=0.02, max_depth=4, subsample=0.5), 'FFN': MLPRegressor(random_state=41, batch_size=100, early_stopping=True, learning_rate='adaptive')}

### June 2020, 2021, 2022 with ExB

In [14]:
p = Preprocessor(drop=drop_cols_ExB)

X_train_validate, Y_train_validate = p.transform([indices_6302020, indices_6302021, indices_6282022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.164376  0.312167  0.002601  0.014312
1     RF   CV  0.152513  0.407783  0.001191  0.010723
2    XGB   CV  0.149475  0.431156  0.001708  0.011677
3    FFN   CV  0.153625  0.399160  0.003373  0.019185

### June 2020, 2021, 2022 without ExB

In [15]:
p = Preprocessor(drop=drop_cols)

X_train_validate, Y_train_validate = p.transform([indices_6302020, indices_6302021, indices_6282022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.164315  0.312693  0.002620  0.013729
1     RF   CV  0.152656  0.406728  0.001593  0.008899
2    XGB   CV  0.149094  0.434048  0.001596  0.011351
3    FFN   CV  0.153919  0.396772  0.002635  0.018542

### June 2020, 2021 with ExB

In [16]:
p = Preprocessor(drop=drop_cols_ExB)

X_train_validate, Y_train_validate = p.transform([indices_6302020, indices_6302021])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.171163  0.104717  0.002611  0.019340
1     RF   CV  0.170464  0.112273  0.003558  0.015263
2    XGB   CV  0.165491  0.163044  0.002882  0.021538
3    FFN   CV  0.170839  0.108538  0.004155  0.012874

### June 2020, 2021 without ExB

In [17]:
p = Preprocessor(drop=drop_cols)

X_train_validate, Y_train_validate = p.transform([indices_6302020, indices_6302021])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.171270  0.103600  0.002640  0.019152
1     RF   CV  0.169562  0.121537  0.003853  0.023344
2    XGB   CV  0.165433  0.163678  0.002965  0.020214
3    FFN   CV  0.170778  0.108595  0.003359  0.029711

### June 2020, 2022 with ExB

In [18]:
p = Preprocessor(drop=drop_cols_ExB)

X_train_validate, Y_train_validate = p.transform([indices_6302020, indices_6282022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

/opt/anaconda3/envs/REU3.9.6/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/opt/anaconda3/envs/REU3.9.6/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.161184  0.439164  0.004744  0.011802
1     RF   CV  0.146450  0.536976  0.004361  0.011816
2    XGB   CV  0.142048  0.564403  0.003615  0.004689
3    FFN   CV  0.146931  0.533807  0.005364  0.021234

### June 2020, 2022 without ExB

In [19]:
p = Preprocessor(drop=drop_cols)

X_train_validate, Y_train_validate = p.transform([indices_6302020, indices_6282022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

/opt/anaconda3/envs/REU3.9.6/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.162377  0.430834  0.004797  0.011967
1     RF   CV  0.146669  0.535634  0.005184  0.015892
2    XGB   CV  0.141623  0.566981  0.003513  0.005659
3    FFN   CV  0.148452  0.524348  0.005833  0.018088

### June 2021, 2022 with ExB

In [20]:
p = Preprocessor(drop=drop_cols_ExB)

X_train_validate, Y_train_validate = p.transform([indices_6302021, indices_6282022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

/opt/anaconda3/envs/REU3.9.6/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.136778  0.374096  0.003460  0.033667
1     RF   CV  0.125517  0.473232  0.004485  0.029853
2    XGB   CV  0.122465  0.499037  0.005360  0.024941
3    FFN   CV  0.127640  0.455141  0.003102  0.025021

### June 2021, 2022 without ExB

In [21]:
p = Preprocessor(drop=drop_cols)

X_train_validate, Y_train_validate = p.transform([indices_6302021, indices_6282022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.137957  0.363668  0.003977  0.029094
1     RF   CV  0.124453  0.482484  0.004480  0.021937
2    XGB   CV  0.122428  0.499319  0.005330  0.025265
3    FFN   CV  0.127542  0.455990  0.003876  0.028967

### July 2020, 2021, 2022 with ExB

In [22]:
p = Preprocessor(drop=drop_cols_ExB)

X_train_validate, Y_train_validate = p.transform([indices_7062020, indices_7122021, indices_7132022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.175353  0.216928  0.002002  0.024097
1     RF   CV  0.162762  0.325682  0.002585  0.009497
2    XGB   CV  0.153004  0.404071  0.001760  0.006041
3    FFN   CV  0.156205  0.378881  0.001742  0.005412

### July 2020, 2021, 2022 without ExB

In [23]:
p = Preprocessor(drop=drop_cols)

X_train_validate, Y_train_validate = p.transform([indices_7062020, indices_7122021, indices_7132022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

/opt/anaconda3/envs/REU3.9.6/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.178282  0.190605  0.002086  0.023320
1     RF   CV  0.161176  0.338840  0.003414  0.012581
2    XGB   CV  0.153290  0.401844  0.001789  0.006402
3    FFN   CV  0.157133  0.371245  0.001006  0.015860

### July 2020, 2021 with ExB

In [24]:
p = Preprocessor(drop=drop_cols_ExB)

X_train_validate, Y_train_validate = p.transform([indices_7062020, indices_7122021])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.170544  0.111601  0.004715  0.021104
1     RF   CV  0.165377  0.164747  0.004584  0.013732
2    XGB   CV  0.162994  0.188514  0.003916  0.012257
3    FFN   CV  0.167026  0.147907  0.004633  0.019538

### July 2020, 2021 without ExB

In [25]:
p = Preprocessor(drop=drop_cols)

X_train_validate, Y_train_validate = p.transform([indices_7062020, indices_7122021])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.173571  0.080127  0.005876  0.021923
1     RF   CV  0.165886  0.159652  0.004901  0.015670
2    XGB   CV  0.162839  0.190108  0.004041  0.010318
3    FFN   CV  0.168216  0.135879  0.005152  0.019046

### July 2020, 2022 with ExB

In [26]:
p = Preprocessor(drop=drop_cols_ExB)

X_train_validate, Y_train_validate = p.transform([indices_7062020, indices_7132022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

/opt/anaconda3/envs/REU3.9.6/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.166059  0.404123  0.001435  0.017772
1     RF   CV  0.163079  0.425864  0.004775  0.013323
2    XGB   CV  0.149372  0.518126  0.002581  0.007772
3    FFN   CV  0.154127  0.486742  0.001477  0.013536

### July 2020, 2022 without ExB

In [27]:
p = Preprocessor(drop=drop_cols)

X_train_validate, Y_train_validate = p.transform([indices_7062020, indices_7132022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.165734  0.406390  0.001381  0.019501
1     RF   CV  0.161835  0.434610  0.005022  0.014882
2    XGB   CV  0.149351  0.518202  0.002223  0.008981
3    FFN   CV  0.153691  0.489803  0.002269  0.008988

### July 2021, 2022 with ExB

In [28]:
p = Preprocessor(drop=drop_cols_ExB)

X_train_validate, Y_train_validate = p.transform([indices_7122021, indices_7132022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

/opt/anaconda3/envs/REU3.9.6/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.130495  0.430767  0.003155  0.019193
1     RF   CV  0.129907  0.436298  0.004618  0.018608
2    XGB   CV  0.127355  0.458292  0.004976  0.019823
3    FFN   CV  0.128479  0.448141  0.003244  0.021576

### July 2021, 2022 without ExB

In [29]:
p = Preprocessor(drop=drop_cols)

X_train_validate, Y_train_validate = p.transform([indices_7122021, indices_7132022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.131146  0.424667  0.002406  0.026022
1     RF   CV  0.129272  0.441868  0.004891  0.018885
2    XGB   CV  0.127143  0.460049  0.004934  0.020617
3    FFN   CV  0.130388  0.431968  0.003731  0.014557