In [41]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor
from IPython.display import display

from Preprocess import Preprocessor
from GridCV import GridCV

In [42]:
drop_cols_ExB = ['Plot', 'Year', 'Date', 'Range', 'Row', 'left', 
                 'top', 'right', 'bottom', 'Mean.Yld.bu.ac', 
                 'Yld Vol(Dr', 'Crop Flw(M', 'Crop Flw(V', 'Elevation(',
                 'Moisture(%', 'BI', 'GLI', 'GLI', 'NGRDI', 'MGRVI', 'RGBVI', 'GRRI', 'VEG', 'ExGR', 'ExG', 'ExR', 'Green'
                ]

drop_cols = ['Plot', 'Year', 'Date', 'Range', 'Row', 'left', 
                 'top', 'right', 'bottom', 'Mean.Yld.bu.ac', 
                 'Yld Vol(Dr', 'Crop Flw(M', 'Crop Flw(V', 'Elevation(',
                 'Moisture(%', 'BI', 'GLI', 'GLI', 'NGRDI', 'MGRVI', 'RGBVI', 'GRRI', 'VEG',
                 'ExB', 'ExGR', 'ExG', 'ExR', 'Green'
            ]

#### Load Field Indices, Set Split Method, and Define Models to be Tested Through Cross Validation

In [43]:
indices_6302020 = pd.read_csv("../Datasets/Indices_Combined/2020/June_30_2020_New.csv")
indices_6302021 = pd.read_csv("../Datasets/Indices_Combined/2021/June_30_2021.csv")
indices_6282022 = pd.read_csv("../Datasets/Indices_Combined/2022/June_28_2022.csv")

indices_7062020 = pd.read_csv("../Datasets/Indices_Combined/2020/July_6_2020_New.csv")
indices_7122021 = pd.read_csv("../Datasets/Indices_Combined/2021/July_12_2021.csv")
indices_7132022 = pd.read_csv("../Datasets/Indices_Combined/2022/July_13_2022.csv")

split_method = 'representative'
cv_models = {'LR': LinearRegression(n_jobs=-1), 'RF': RandomForestRegressor(n_jobs=-1, random_state=41, max_features='sqrt', max_depth=6, max_samples=50), 'XGB': XGBRegressor(eta=0.02, max_depth=4, subsample=0.5), 'FFN': MLPRegressor(random_state=41, batch_size=100, early_stopping=True, learning_rate='adaptive')}

### June 2020, 2021, 2022 with ExB

In [44]:
p = Preprocessor(drop=drop_cols_ExB)

X_train_validate, Y_train_validate = p.transform([indices_6302020, indices_6302021, indices_6282022])

folds = GridCV.split([indices_6302020, indices_6302021, indices_6282022], n_splits=12, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

/opt/anaconda3/envs/REU3.9.6/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.181614  0.098027  0.018063  0.131979
1           RF   CV  0.169064  0.211274  0.018105  0.162466
2          XGB   CV  0.169673  0.210480  0.013456  0.112247
3          FFN   CV  0.172368  0.182878  0.019930  0.161399

### June 2020, 2021, 2022 without ExB

In [45]:
p = Preprocessor(drop=drop_cols)

X_train_validate, Y_train_validate = p.transform([indices_6302020, indices_6302021, indices_6282022])

folds = GridCV.split([indices_6302020, indices_6302021, indices_6282022], n_splits=12, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

/opt/anaconda3/envs/REU3.9.6/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.180396  0.109969  0.017740  0.129763
1           RF   CV  0.171239  0.197337  0.015981  0.117960
2          XGB   CV  0.169642  0.211006  0.013304  0.110272
3          FFN   CV  0.166740  0.238528  0.010176  0.086036

### June 2020, 2021 with ExB

In [46]:
p = Preprocessor(drop=drop_cols_ExB)

X_train_validate, Y_train_validate = p.transform([indices_6302020, indices_6302021])

folds = GridCV.split([indices_6302020, indices_6302021], n_splits=6, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.185752 -0.113663  0.017703  0.079890
1           RF   CV  0.188755 -0.149924  0.017347  0.070156
2          XGB   CV  0.187948 -0.139763  0.018602  0.087302
3          FFN   CV  0.186841 -0.127404  0.016677  0.069710

### June 2020, 2021 without ExB

In [47]:
p = Preprocessor(drop=drop_cols)

X_train_validate, Y_train_validate = p.transform([indices_6302020, indices_6302021])

folds = GridCV.split([indices_6302020, indices_6302021], n_splits=6, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

/opt/anaconda3/envs/REU3.9.6/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.184655 -0.100938  0.017534  0.083503
1           RF   CV  0.187042 -0.129224  0.017085  0.068190
2          XGB   CV  0.188018 -0.140617  0.018473  0.085130
3          FFN   CV  0.185111 -0.108994  0.014140  0.066865

### June 2020, 2022 with ExB

In [48]:
p = Preprocessor(drop=drop_cols_ExB)

X_train_validate, Y_train_validate = p.transform([indices_6302020, indices_6282022])

folds = GridCV.split([indices_6302020, indices_6282022], n_splits=6, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.205517 -0.051462  0.015611  0.125633
1           RF   CV  0.175575  0.244828  0.024281  0.060112
2          XGB   CV  0.172272  0.274249  0.023884  0.041154
3          FFN   CV  0.186408  0.145762  0.020472  0.019056

### June 2020, 2022 without ExB

In [49]:
p = Preprocessor(drop=drop_cols)

X_train_validate, Y_train_validate = p.transform([indices_6302020, indices_6282022])

folds = GridCV.split([indices_6302020, indices_6282022], n_splits=6, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

/opt/anaconda3/envs/REU3.9.6/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.207027 -0.064206  0.016925  0.109735
1           RF   CV  0.179417  0.212387  0.023704  0.032561
2          XGB   CV  0.170846  0.286163  0.023995  0.046319
3          FFN   CV  0.186995  0.135477  0.016116  0.048360

### June 2021, 2022 with ExB

In [50]:
p = Preprocessor(drop=drop_cols_ExB)

X_train_validate, Y_train_validate = p.transform([indices_6302021, indices_6282022])

folds = GridCV.split([indices_6302021, indices_6282022], n_splits=6, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

/opt/anaconda3/envs/REU3.9.6/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.167751  0.025478  0.011634  0.372119
1           RF   CV  0.151379  0.240261  0.007708  0.157780
2          XGB   CV  0.150583  0.250428  0.010350  0.150396
3          FFN   CV  0.144501  0.305327  0.005681  0.153334

### June 2021, 2022 without ExB

In [51]:
p = Preprocessor(drop=drop_cols)

X_train_validate, Y_train_validate = p.transform([indices_6302021, indices_6282022])

folds = GridCV.split([indices_6302021, indices_6282022], n_splits=6, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

/opt/anaconda3/envs/REU3.9.6/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.169171  0.022513  0.008422  0.323760
1           RF   CV  0.155769  0.193828  0.012980  0.187203
2          XGB   CV  0.151033  0.245539  0.010433  0.153627
3          FFN   CV  0.144709  0.310031  0.009824  0.125846

### July 2020, 2021, 2022 with ExB

In [52]:
p = Preprocessor(drop=drop_cols_ExB)

X_train_validate, Y_train_validate = p.transform([indices_7062020, indices_7122021, indices_7132022])

folds = GridCV.split([indices_7062020, indices_7122021, indices_7132022], n_splits=9, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.212693 -0.180905  0.027408  0.231231
1           RF   CV  0.193622  0.016908  0.037417  0.299166
2          XGB   CV  0.185537  0.103942  0.027169  0.189321
3          FFN   CV  0.180481  0.152465  0.026350  0.178028

### July 2020, 2021, 2022 without ExB

In [53]:
p = Preprocessor(drop=drop_cols)

X_train_validate, Y_train_validate = p.transform([indices_7062020, indices_7122021, indices_7132022])

folds = GridCV.split([indices_7062020, indices_7122021, indices_7132022], n_splits=9, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

/opt/anaconda3/envs/REU3.9.6/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.216389 -0.221845  0.032713  0.272820
1           RF   CV  0.192747  0.027937  0.034975  0.272771
2          XGB   CV  0.185952  0.099944  0.027185  0.189753
3          FFN   CV  0.187954  0.072263  0.038020  0.300526

### July 2020, 2021 with ExB

In [54]:
p = Preprocessor(drop=drop_cols_ExB)

X_train_validate, Y_train_validate = p.transform([indices_7062020, indices_7122021])

folds = GridCV.split([indices_7062020, indices_7122021], n_splits=6, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.195259 -0.230685  0.017864  0.075286
1           RF   CV  0.189077 -0.159158  0.014675  0.100023
2          XGB   CV  0.192801 -0.199855  0.017928  0.079126
3          FFN   CV  0.191843 -0.188036  0.023679  0.159993

### July 2020, 2021 without ExB

In [55]:
p = Preprocessor(drop=drop_cols)

X_train_validate, Y_train_validate = p.transform([indices_7062020, indices_7122021])

folds = GridCV.split([indices_7062020, indices_7122021], n_splits=6, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.203029 -0.331375  0.021371  0.136497
1           RF   CV  0.190029 -0.169847  0.017787  0.126386
2          XGB   CV  0.193303 -0.206409  0.018503  0.093129
3          FFN   CV  0.193017 -0.202104  0.019758  0.103691

### July 2020, 2022 with ExB

In [56]:
p = Preprocessor(drop=drop_cols_ExB)

X_train_validate, Y_train_validate = p.transform([indices_7062020, indices_7132022])

folds = GridCV.split([indices_7062020, indices_7132022], n_splits=6, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.203419 -0.016481  0.043966  0.260482
1           RF   CV  0.199607  0.031071  0.057819  0.332059
2          XGB   CV  0.195774  0.069331  0.051288  0.270052
3          FFN   CV  0.178084  0.230324  0.040264  0.171750

### July 2020, 2022 without ExB

In [57]:
p = Preprocessor(drop=drop_cols)

X_train_validate, Y_train_validate = p.transform([indices_7062020, indices_7132022])

folds = GridCV.split([indices_7062020, indices_7132022], n_splits=6, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

/opt/anaconda3/envs/REU3.9.6/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.188454  0.139534  0.047501  0.230750
1           RF   CV  0.197046  0.056807  0.056010  0.313227
2          XGB   CV  0.195239  0.074483  0.051372  0.270369
3          FFN   CV  0.187112  0.150294  0.048662  0.242917

### July 2021, 2022 with ExB

In [58]:
p = Preprocessor(drop=drop_cols_ExB)

X_train_validate, Y_train_validate = p.transform([indices_7122021, indices_7132022])

folds = GridCV.split([indices_7122021, indices_7132022], n_splits=6, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.135494  0.397434  0.007468  0.088655
1           RF   CV  0.139540  0.361401  0.008791  0.096145
2          XGB   CV  0.139897  0.367158  0.013646  0.043215
3          FFN   CV  0.134216  0.407043  0.006418  0.095970

### July 2021, 2022 without ExB

In [59]:
p = Preprocessor(drop=drop_cols)

X_train_validate, Y_train_validate = p.transform([indices_7122021, indices_7132022])

folds = GridCV.split([indices_7122021, indices_7132022], n_splits=6, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.135313  0.397193  0.006513  0.098048
1           RF   CV  0.136882  0.386909  0.008612  0.081825
2          XGB   CV  0.139733  0.368134  0.013233  0.045595
3          FFN   CV  0.135302  0.399850  0.007744  0.084671