In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor
from IPython.display import display

from Preprocess import Preprocessor
from RandomCV import RandomCV

### Load Field Indices and Define Models to be Tested Through Cross Validation

In [2]:
indices_6302020 = pd.read_csv("../Datasets/Indices_Combined/2020/June_30_2020_New.csv")
indices_6302021 = pd.read_csv("../Datasets/Indices_Combined/2021/June_30_2021.csv")
indices_6282022 = pd.read_csv("../Datasets/Indices_Combined/2022/June_28_2022.csv")

indices_7062020 = pd.read_csv("../Datasets/Indices_Combined/2020/July_6_2020_New.csv")
indices_7122021 = pd.read_csv("../Datasets/Indices_Combined/2021/July_12_2021.csv")
indices_7132022 = pd.read_csv("../Datasets/Indices_Combined/2022/July_13_2022.csv")

cv_models = {'LR': LinearRegression(n_jobs=-1), 'RF': RandomForestRegressor(n_jobs=-1, random_state=41, max_features='sqrt', max_depth=6, max_samples=50), 'XGB': XGBRegressor(eta=0.02, max_depth=4, subsample=0.5), 'FFN': MLPRegressor(random_state=41, batch_size=100, early_stopping=True, learning_rate='adaptive')}

### June 2020, 2021, 2022

In [3]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_6302020, indices_6302021, indices_6282022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.157047  0.372008  0.000761  0.012367
1     RF   CV  0.152819  0.405528  0.002133  0.008084
2    XGB   CV  0.149485  0.431056  0.001660  0.012803
3    FFN   CV  0.153323  0.401503  0.001359  0.009832

### June 2020, 2021

In [4]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_6302020, indices_6302021])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.168299  0.134338  0.003383  0.027905
1     RF   CV  0.169999  0.116869  0.003204  0.023016
2    XGB   CV  0.165207  0.166098  0.003148  0.015359
3    FFN   CV  0.170694  0.109916  0.003444  0.010197

### June 2020, 2022

In [5]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_6302020, indices_6282022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.151451  0.504636  0.002877  0.009016
1     RF   CV  0.146207  0.538445  0.004675  0.016161
2    XGB   CV  0.142627  0.560885  0.003820  0.004203
3    FFN   CV  0.151217  0.506461  0.006109  0.019857

### June 2021, 2022

In [6]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_6302021, indices_6282022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.135042  0.389340  0.004784  0.045634
1     RF   CV  0.125409  0.474543  0.004257  0.018991
2    XGB   CV  0.122563  0.498477  0.005122  0.016895
3    FFN   CV  0.129116  0.441329  0.001204  0.039995

### July 2020, 2021, 2022

In [7]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_7062020, indices_7122021, indices_7132022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.167900  0.282032  0.001595  0.022956
1     RF   CV  0.157411  0.369255  0.001907  0.006717
2    XGB   CV  0.152923  0.404679  0.001384  0.005679
3    FFN   CV  0.157157  0.371076  0.001067  0.015287

### July 2020, 2021

In [8]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_7062020, indices_7122021])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.170097  0.116226  0.003829  0.009742
1     RF   CV  0.165438  0.164225  0.005390  0.020816
2    XGB   CV  0.162709  0.191343  0.003862  0.011857
3    FFN   CV  0.168057  0.137659  0.006766  0.033065

### July 2020, 2022

In [9]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_7062020, indices_7132022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.160726  0.441757  0.001155  0.017269
1     RF   CV  0.156890  0.468484  0.003049  0.005544
2    XGB   CV  0.148894  0.521162  0.002350  0.008786
3    FFN   CV  0.153998  0.487492  0.001934  0.018273

### July 2021, 2022

In [13]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_7122021, indices_7132022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.129915  0.435314  0.002950  0.029889
1     RF   CV  0.129898  0.436328  0.004283  0.016478
2    XGB   CV  0.127600  0.456410  0.004919  0.012339
3    FFN   CV  0.128590  0.447127  0.002787  0.020810