In [2]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPRegressor

from xgboost import XGBRegressor
from IPython.display import display

from Preprocess import Preprocessor
from RandomCV import RandomCV

### Load Field Indices and Define Models to be Tested Through Cross Validation

In [3]:
indices_6302020 = pd.read_csv("../Datasets/Indices_Combined/2020/June_30_2020_New.csv")
indices_6302021 = pd.read_csv("../Datasets/Indices_Combined/2021/June_30_2021.csv")
indices_6282022 = pd.read_csv("../Datasets/Indices_Combined/2022/June_28_2022.csv")

indices_7062020 = pd.read_csv("../Datasets/Indices_Combined/2020/July_6_2020_New.csv")
indices_7122021 = pd.read_csv("../Datasets/Indices_Combined/2021/July_12_2021.csv")
indices_7132022 = pd.read_csv("../Datasets/Indices_Combined/2022/July_13_2022.csv")

cv_models = {'LR': LinearRegression(n_jobs=-1), 'RF': RandomForestRegressor(n_jobs=-1, random_state=41), 'XGB': XGBRegressor(), 'FFN': MLPRegressor(random_state=41)}

### June 2020, 2021, 2022

In [4]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_6302020, indices_6302021, indices_6282022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.157047  0.372008  0.000761  0.012367
1     RF   CV  0.148411  0.438710  0.002137  0.027648
2    XGB   CV  0.158461  0.360164  0.002162  0.030208
3    FFN   CV  0.160420  0.344898  0.002226  0.010494

### June 2020, 2021

In [14]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_6302020, indices_6302021])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.168299  0.134338  0.003383  0.027905
1     RF   CV  0.167003  0.147401  0.002251  0.027756
2    XGB   CV  0.177261  0.039108  0.001605  0.037689
3    FFN   CV  0.172204  0.094076  0.003473  0.012263

### June 2020, 2022

In [15]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_6302020, indices_6282022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.151451  0.504636  0.002877  0.009016
1     RF   CV  0.142318  0.562438  0.002447  0.012848
2    XGB   CV  0.151834  0.501640  0.002354  0.022709
3    FFN   CV  0.156390  0.471955  0.003959  0.008895

### June 2021, 2022

In [16]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_6302021, indices_6282022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.135042  0.389340  0.004784  0.045634
1     RF   CV  0.122639  0.496803  0.005658  0.040371
2    XGB   CV  0.133396  0.404828  0.004144  0.033343
3    FFN   CV  0.132919  0.409072  0.003166  0.028135

### July 2020, 2021, 2022

In [17]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_7062020, indices_7122021, indices_7132022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.167900  0.282032  0.001595  0.022956
1     RF   CV  0.153656  0.398886  0.001945  0.013328
2    XGB   CV  0.162272  0.329706  0.003391  0.017239
3    FFN   CV  0.161049  0.339278  0.002169  0.026628

### July 2020, 2021

In [18]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_7062020, indices_7122021])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.170097  0.116226  0.003829  0.009742
1     RF   CV  0.169344  0.123290  0.001874  0.028242
2    XGB   CV  0.180348  0.005668  0.002569  0.033955
3    FFN   CV  0.169392  0.123785  0.005133  0.016768

### July 2020, 2022

In [19]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_7062020, indices_7132022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.160726  0.441757  0.001155  0.017269
1     RF   CV  0.146588  0.535705  0.001723  0.013728
2    XGB   CV  0.155925  0.474894  0.003811  0.016444
3    FFN   CV  0.156653  0.469736  0.002550  0.018383

### July 2021, 2022

In [20]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_7122021, indices_7132022])

random_validator = RandomCV(models=cv_models)

random_results = random_validator.results(X_train_validate, Y_train_validate)

display(random_results)

  Random TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR   CV  0.129915  0.435314  0.002950  0.029889
1     RF   CV  0.135191  0.389048  0.003966  0.025938
2    XGB   CV  0.145643  0.289146  0.003082  0.054427
3    FFN   CV  0.131239  0.424224  0.003105  0.020075