In [2]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor
from IPython.display import display

from Preprocess import Preprocessor
from GridCV import GridCV

#### Load Field Indices, Set Split Method, and Define Models to be Tested Through Cross Validation

In [3]:
indices_6302020 = pd.read_csv("../Datasets/Indices_Combined/2020/June_30_2020_New.csv")
indices_6302021 = pd.read_csv("../Datasets/Indices_Combined/2021/June_30_2021.csv")
indices_6282022 = pd.read_csv("../Datasets/Indices_Combined/2022/June_28_2022.csv")

indices_7062020 = pd.read_csv("../Datasets/Indices_Combined/2020/July_6_2020_New.csv")
indices_7122021 = pd.read_csv("../Datasets/Indices_Combined/2021/July_12_2021.csv")
indices_7132022 = pd.read_csv("../Datasets/Indices_Combined/2022/July_13_2022.csv")

split_method = 'representative'
cv_models = {'LR': LinearRegression(n_jobs=-1), 'RF': RandomForestRegressor(n_jobs=-1, random_state=41, max_features='sqrt', max_depth=6, max_samples=50), 'XGB': XGBRegressor(eta=0.02, max_depth=4, subsample=0.5), 'FFN': MLPRegressor(random_state=41, batch_size=100, early_stopping=True, learning_rate='adaptive')}

### June 2020, 2021, 2022

In [4]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_6302020, indices_6302021, indices_6282022])

folds = GridCV.split([indices_6302020, indices_6302021, indices_6282022], n_splits=12, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.193371 -0.050004  0.044494  0.434109
1           RF   CV  0.172195  0.188128  0.015388  0.114453
2          XGB   CV  0.171423  0.191819  0.013016  0.127693
3          FFN   CV  0.173322  0.177873  0.015434  0.112278

### June 2020, 2021

In [8]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_6302020, indices_6302021])

folds = GridCV.split([indices_6302020, indices_6302021], n_splits=6, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.226115 -0.696312  0.056907  0.717223
1           RF   CV  0.186795 -0.125971  0.017706  0.075486
2          XGB   CV  0.189406 -0.157623  0.017989  0.077665
3          FFN   CV  0.188638 -0.149799  0.014726  0.036707

### June 2020, 2022

In [25]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_6302020, indices_6282022])

folds = GridCV.split([indices_6302020, indices_6282022], n_splits=6, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.197328  0.056367  0.042246  0.181811
1           RF   CV  0.188078  0.123255  0.020978  0.126850
2          XGB   CV  0.177633  0.224726  0.019732  0.008294
3          FFN   CV  0.192312  0.088495  0.020538  0.059912

### June 2021, 2022

In [26]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_6302021, indices_6282022])

folds = GridCV.split([indices_6302021, indices_6282022], n_splits=6, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.153982  0.218409  0.007891  0.137290
1           RF   CV  0.150731  0.258836  0.013700  0.102090
2          XGB   CV  0.153893  0.223104  0.010481  0.121031
3          FFN   CV  0.151382  0.227372  0.007452  0.218502

### July 2020, 2021, 2022

In [27]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_7062020, indices_7122021, indices_7132022])

folds = GridCV.split([indices_7062020, indices_7122021, indices_7132022], n_splits=9, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.233119 -0.439861  0.046818  0.457935
1           RF   CV  0.185587  0.100901  0.031521  0.231758
2          XGB   CV  0.183754  0.121959  0.025795  0.174689
3          FFN   CV  0.183369  0.126091  0.024523  0.162687

### July 2020, 2021

In [28]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_7062020, indices_7122021])

folds = GridCV.split([indices_7062020, indices_7122021], n_splits=6, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.314565 -2.839038  0.166674  3.555405
1           RF   CV  0.183678 -0.093242  0.017099  0.119422
2          XGB   CV  0.189939 -0.164892  0.016383  0.057729
3          FFN   CV  0.190587 -0.174304  0.015806  0.072018

### July 2020, 2022

In [29]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_7062020, indices_7132022])

folds = GridCV.split([indices_7062020, indices_7132022], n_splits=6, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.187005  0.151946  0.045275  0.212786
1           RF   CV  0.189293  0.130093  0.050668  0.261265
2          XGB   CV  0.189973  0.124705  0.049432  0.249556
3          FFN   CV  0.183767  0.180033  0.040695  0.177183

### July 2021, 2022

In [30]:
p = Preprocessor()

X_train_validate, Y_train_validate = p.transform([indices_7122021, indices_7132022])

folds = GridCV.split([indices_7122021, indices_7132022], n_splits=6, method=split_method)

grid_validator = GridCV(models=cv_models)

grid_results = grid_validator.results(X_train_validate, Y_train_validate, folds)

display(grid_results)

  Spatial Grid TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0           LR   CV  0.139365  0.370801  0.013188  0.052823
1           RF   CV  0.135652  0.401024  0.010489  0.063011
2          XGB   CV  0.140258  0.362939  0.013174  0.050090
3          FFN   CV  0.134833  0.405169  0.008331  0.077957