In [1]:
import pandas as pd
import numpy as np
from Preprocessing import CombinedPreprocessor
from RandomCV import RandomCV
from GroupKFoldCV import GroupKFoldCV
from SpatialPlusCV import SpatialPlusCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor

from IPython.display import display

In [2]:
p = CombinedPreprocessor()

indices_6182020 = pd.read_csv("../Datasets/Indices_Combined/2020/June_18_2020_New.csv")
indices_6232020 = pd.read_csv("../Datasets/Indices_Combined/2020/June_23_2020_New.csv")
indices_6302020 = pd.read_csv("../Datasets/Indices_Combined/2020/June_30_2020_New.csv")
indices_7062020 = pd.read_csv("../Datasets/Indices_Combined/2020/July_6_2020_New.csv")

X_train_validate, X_test, Y_train_validate, Y_test = p.transform([indices_6182020, indices_6232020, indices_6302020], indices_7062020)

random_validator = RandomCV(models={'LR': LinearRegression(n_jobs=-1), 'RF': RandomForestRegressor(n_jobs=-1, random_state=41), 'XGB': XGBRegressor()})
gkf_validator = GroupKFoldCV(models={'LR': LinearRegression(n_jobs=-1), 'RF': RandomForestRegressor(n_jobs=-1, random_state=41), 'XGB': XGBRegressor()})
sp_validator = SpatialPlusCV(models={'LR': LinearRegression(n_jobs=-1), 'RF': RandomForestRegressor(n_jobs=-1, random_state=41), 'XGB': XGBRegressor()})
random_results = random_validator.results(X_train_validate, X_test, Y_train_validate, Y_test)
gkf_results = gkf_validator.results(X_train_validate, X_test, Y_train_validate, Y_test)
sp_results = sp_validator.results(X_train_validate, X_test, Y_train_validate, Y_test)

display(random_results, gkf_results, sp_results)

SP RMSE TEST:  [0.4986403755163278, 0.24953112783986203, 0.24251268493397596, 0.25976038836706017]
SP R2 TEST:  [-4.404117341514294, -0.3533164088707972, -0.2782588500947203, -0.4665461644981648]
SP RMSE TEST:  [0.20827010532553417, 0.2797426534640142, 0.2908985505294995, 0.2760692941317927]
SP R2 TEST:  [0.057234325233873284, -0.7008549120007073, -0.8392171296800981, -0.6564796244598863]
SP RMSE TEST:  [0.22418764203198033, 0.2974915886336279, 0.29945209547418733, 0.2647370148341428]
SP R2 TEST:  [-0.09237873554229736, -0.9235314130783081, -0.948967456817627, -0.5232782363891602]

  Random  TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0     LR    CV  0.144977  0.539791  0.003391  0.020246
1     LR  TEST  0.255023 -0.415354  0.009140  0.102983
2     RF    CV  0.089465  0.824632  0.002430  0.010718
3     RF  TEST  0.279579 -0.713036  0.025530  0.301651
4    XGB    CV  0.095147  0.801422  0.004236  0.017975
5    XGB  TEST  0.271757 -0.613197  0.019262  0.234769

  GroupKFold  TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0         LR    CV  0.188382  0.110420  0.063029  0.485202
1         LR  TEST  0.305546 -1.070964  0.043889  0.598827
2         RF    CV  0.134314  0.561976  0.030476  0.144375
3         RF  TEST  0.257513 -0.498058  0.051113  0.527299
4        XGB    CV  0.152184  0.433280  0.041887  0.246987
5        XGB  TEST  0.258002 -0.491383  0.045314  0.491948

  Spatial+  TYPE  RMSE_AVG    R2_AVG  RMSE STD    R2 STD
0       LR    CV  0.149953  0.445614  0.022800  0.120852
1       LR  TEST  0.312611 -1.375560  0.107579  1.749823
2       RF    CV  0.109261  0.684841  0.042935  0.224709
3       RF  TEST  0.263745 -0.534829  0.032491  0.348409
4      XGB    CV  0.112380  0.668089  0.042845  0.226854
5      XGB  TEST  0.271467 -0.622039  0.030582  0.349311